export const strings = {
	error: "Error",
	tryAgain: "Reintentar",
	wrongUsernameOrPassword: "Usuario o contraseña incorrecto.",
	emptyUsernameOrPassword: "Usuario o contraseña no pueden estar en blanco.",
	logIn: "Inicia Sesion",
	usernameWarningMessage: "El usuario debe tener 3 caracteres.",
	passwordWarningMessage: "La contraseña debe tener 3 caracteres.",
	troubleLogIn: "¿Problemas para acceder?",
	access: "Acceder",
	newUser: "¿Usuario nuevo?",
	signUp: "Regístrate",
	user: "Usuario",
	password: "Contraseña",
};
