export const strings = {
  emptyCredentials: "Cédula o contraseña no pueden estar en blanco.",
  tryAgain: "Reintentar",
  ohRight: "Entendido",
  error: "Error",
  haveAnAccount: "¿Tienes una Cuenta?",
  next: "Siguiente",
  troubleSigningIn: "¿Problemas para registrarte?",
  password: "Contraseña.",
  passwordWarningMessage: "La contraseña debe tener 3 caracteres.",
  usernameWarningMessage: "El usuario debe tener 3 caracteres.",
  signUp: "Registrate",
  identificationNumber: "Cédula",
  warning: "Aviso",
  messageAfterSignup: "Pronto seras contactado por uno de nuestros asistentes.",
  access: "Entrar",
};
